version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: NexTaskDB
    environment:
      POSTGRES_DB: nextask_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    restart: always